import { UserDocument, UserModel } from "../models/user.model";
import { AppError } from "../utils/app.error";

export interface Users {
  name: string;
  email: string;
  age: number;
  id: string;
}

export const createUser = async (name: string, email: string, age: number) => {
  const newUser: UserDocument = {
    name,
    email,
    age,
    id: " ", // This will be auto-generated by MongoDB
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  // if creating user incorrectly, throw error with error code which is 400

  const existingUser = await UserModel.findOne({ email: email });
  if (existingUser) {
    throw new AppError("User with this email already exists", 409);
  }

  if (!name || !email || age === undefined) {
    throw new AppError("Invalid user data", 400);
  }

  const createdUser = await UserModel.create(newUser);
  return createdUser;
};

export const getAllUsers = async () => {
  const users = await UserModel.find();
  if (users.length === 0) {
    throw new AppError("No users found", 404);
  }
  return users;
};

export const getUserById = async (id: string) => {
  const getUserId = await UserModel.findById(id);
  if (!getUserId) {
    throw new AppError("User not found", 404);
  }
  return getUserId;
};

//
export const updateById = async (
  id: string,
  updateData: Partial<UserDocument>,
) => {
  const updatedUser = await UserModel.findByIdAndUpdate(id, updateData, {
    new: true,
    runValidators: true,
  });
  if (!updatedUser) {
    throw new AppError("User not found", 404);
  }
  return updatedUser;
};

export const deleteById = async (id: string) => {
  return await UserModel.findByIdAndDelete(id);
};
